[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules"]

[rpc_endpoints]
rsk = "${RSK_RPC_URL}"
rskMainnet = "${RSK_MAINNET_RPC}"

[etherscan]
rskTestnet = {key = "${RSKSCAN_KEY}"}

[chain]
default = 31
